---
language: python
services: docker

env:
  matrix:
    - platform_image: centos:7
    - platform_image: ubuntu:18.04
    - platform_image: ubuntu:16.04

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
