---
- name: Install prerequisites
  package:
    name: "{{ item }}"
  with_items:
    - curl
    - rlwrap

- name: Check if Clojure has been installed already
  stat:
    path: "{{ clojure_install_path }}"
  register: clojure_install_path_status

- name: Download Clojure
  get_url:
    url: "{{ clojure_download_url }}"
    dest: "{{ clojure_install_script }}"
    force: false
    mode: 0755
  when: clojure_install_path_status.stat.isdir is not defined
  notify:
    - Install Clojure
    - Remove Clojure install script

- name: Ensure Clojure is installed
  meta: flush_handlers

- name: Download Leiningen.
  get_url:
    url: "{{ lein_download_url }}"
    dest: "{{ lein_install_path }}"
    force: false
    mode: 0755
