---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: ${platform_image:-"centos:7"}
provisioner:
  name: ansible
verifier:
  name: ansible
